name: create-package
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  create-package:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_NAME: ${{ github.event.repository.name }}
      TAG_NAME: ${{ github.ref_name }}
    steps:
      - name: Create archive name
        run: |
          PLUGIN_NAME=$(echo $REPOSITORY_NAME | sed -e 's/^.*-//')
          echo "PLUGIN_NAME=$PLUGIN_NAME" >> $GITHUB_ENV
          echo "ARCHIVE_NAME=$PLUGIN_NAME-$TAG_NAME" >> $GITHUB_ENV
      - name: Get files into context
        uses: actions/checkout@v3
      - name: Create archive
        run: |
          npm i tar-to-zip -g
          tar --transform "s%^%$PLUGIN_NAME/%" --show-transformed -zcvf "$ARCHIVE_NAME".tar.gz ajax drawio drawio-integration front inc locales sql graph.png *.xml *.php  LICENSE README.md INSTALL.md
          tar2zip "$ARCHIVE_NAME".tar.gz
      - name: Upload tarfile to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{env.ARCHIVE_NAME}}.tar.gz
          tag: ${{env.TAG_NAME}}
          overwrite: true
          prerelease: false
          release_name: ${{github.event.release.name}}
          body: ${{github.event.release.body}}
